name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build-windows:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v4
          with:
            submodules: recursive
        - uses: ilammy/msvc-dev-cmd@v1.13.0
          with:
            arch: x86
        
        - name: Install Windows boost
          uses: MarkusJx/install-boost@v2.4.5
          id: install-boost
          with:
        # REQUIRED: Specify the required boost version
        # A list of supported versions can be found here:
        # https://github.com/MarkusJx/prebuilt-boost/blob/main/versions-manifest.json
            boost_version: 1.79.0
        # OPTIONAL: Specify a custom install location
            boost_install_dir: C:\boost_1_79_0
        # OPTIONAL: Specify an architecture
            arch: x86
            platform_version: 2022
            toolset: msvc
          
        - name: Configure CMake
          run: |
            cmake . -DCMAKE_BUILD_TYPE=Release -B build -DCMAKE_INSTALL_PREFIX=cmake_install_dir -DBOOST_ROOT=${{ steps.install-boost.outputs.BOOST_ROOT }} -G "NMake Makefiles"
            cd build
            nmake
          
        - name: Create Artifacts
          uses: actions/upload-artifact@v4
          with:
            name: Windows-Artifacts
            path: build/
          if: always()
          
  ubuntu-build:
    name: Ubuntu Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Install Linux boost
        uses: MarkusJx/install-boost@v2.4.5
        id: install-boost
        with:
      # REQUIRED: Specify the required boost version
      # A list of supported versions can be found here:
      # https://github.com/MarkusJx/prebuilt-boost/blob/main/versions-manifest.json
          boost_version: 1.79.0
      # OPTIONAL: Specify a custom install location
          boost_install_dir: /home/runner/boost_1_79_0
      # OPTIONAL: Specify an architecture
          arch: x86
          platform_version: 20.04
      
      - name: Configure CMake
        run: |
          cmake . -DCMAKE_BUILD_TYPE=Release -B build -DCMAKE_INSTALL_PREFIX=cmake_install_dir -DBOOST_ROOT=${{ steps.install-boost.outputs.BOOST_ROOT }}
          make -C build
        
      - name: Create Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Ubuntu-Artifacts
          path: build/
        if: always()
